
# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

# Default build settings
[build]
  publish = "public"
  command = "git submodule update -f --init --recursive && yarn install && hugo"

[context.production.environment]
  HUGO_VERSION = "0.73.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.73.0"